### ISSUE TITLE
how to work with more blocks (than just "block content") in parent/child? 

### ISSUE THREAD

**Issue by maniqui** [mohitsinghs/gulp-nunjucks-md#2]
#One key advantage of using templating systems like nunjucks is having the ability of defining blocks on the parent template and populate/extend them (via `{{ super () }}`) on the child template. 

I've worked with nunjucks + gulp in the past and didn't have any problem doing that, afaicr.
But now that I'm using `gulp-nuncjucks-md` (mostly to have the ability of using front-matter), I can't find the way of defining new blocks in the parent template and filling in them from within the child template.
What am I missing?

Thanks.

**Comment by mohitsinghs** [comment]
You can still use `{{ super() }}` on the child template in the same way you will do in a normal nunjucks child templates. Even the name `content` is optional. You can change it in options. 

Suppose in `parent.njk` we have somewhere
```nunjucks
 {% block content %}{% endblock %}
```
and in `child.njk` we extend `parent.njk` and modify `content` block.

```nunjucks
{% extends "parent.njk" %}
{% block content %}
<p>from child layout</p>
{% endblock %}
```
This plugin converts

```yaml
---
layout: child
title: "Page Title"
description: "Some Awesome Description"
---
{{ super() }}
```

to 

```nunjucks
{% extends "layout.njk" %}
{% block content %}
<p>lorem epsum dolor</p>
{% endblock %}
```

and appends your frontmatter data under page object so that you can access it in parent as well as child.

We can use `{{ super() }}` from our page with frontmatter to embed whatever content we have defined in our content block in parent template. **After all, We are converting our page to extend the specified template and wrapping a content (or any name you assigned to it) block around it**. I hope this can help.

**Comment by maniqui** [comment]
Thanks for your prompt reply, @mohitsinghs.
I may have not explained myself properly. I get what you are saying, as it's how I'm using nunjucks + your plugin. 

What I'm trying to say is that I cannot find a way of defining extra blocks in `parent.njk` and populating them on `child.njk`.

Suppose that I want to define some other blocks in `parent.njk` (as you would do in "normal" nunjuck). like this:

```
{% block css %}
<link href="main.css" />
{% endblock %}
...
{% block content %}{% endblock %}
...
{% block extra_info %}{% endblock %}
...
{% block js_bottom %}
<script src="jquery.js" />
{% endblock %}
```

And then populate/expand those blocks on `child.njk`, like this:

```
---
layout: child
title: "Page Title"
description: "Some Awesome Description"
---

{% block css %}
{{ super() }}
<link href="extra_styles_for_fancy_effect.css" />
{% endblock %}

{% block content %}
My main content of Super Awesome Page.
{% endblock %}

{% block extra_info %}
Some extra info only for this page.
{% endblock %}

{% block js_bottom %}
{{ super() }}
<script src="fancy_effect.js" />
{% endblock %}
```

That's "normal" nunjucks (well, if we don't consider the front-matter chunk, of course). But I can't get that working with `gulp-nunjucks-md` :(
I've yet to check if that works with "standard" `gulp-nunjucks-render` (I think it does), although I don't want to miss the ability to use front-matter.

Thanks for your time.

**Comment by mohitsinghs** [comment]
Thanks for explaining your question (as I was expecting) . We can actually do that but in that case there should be an option to turn content blocks on and off I guess. As for now content blocks are wrapped to the whole page and that's why its not working as you are expecting. We can change this behaviour but in that case we will need to specify content block in our file with frontmatter ( as you did in your example) . 

How about having that option ( to switch wrapping of content block) in file level ( in frontmatter) and global configuration.

**Comment by mohitsinghs** [comment]
Done. Now from v1.2.0 use can set `useBlock` option to false globally or at file level in frontmatter. 
Your frontmatter should now be
```yaml
---
layout: child
useBlock: false
title: "Page Title"
description: "Some Awesome Description"
---
```
And then your example will work fine. 😃 
Can we now close this issue.

**Comment by maniqui** [comment]
I did a quick test and it seems to be working as advertised :)
Thank you very much.

btw, one little thing regarding this thread: I think you (and then me, as I copy-pasted your code) made a little mistake on the frontmatter snippet used as example, as it reads `layout: child` instead of `layout: parent`. Right?

**Comment by mohitsinghs** [comment]
Regrading the mistake, Our examples were different and I had a `child.njk` which extends to `parent.njk` and a page which extends to `child.njk` and that's why I used `layout: child` in my example while in your case there was only one parent layout `parent.njk` so `layout: parent` should be written instead of `layout: child`. Anyway I have corrected both of examples.
I am closing this issue as it is fixed now. Thanks again for your idea.
