### ISSUE TITLE
Incorrectly macro call

### ISSUE THREAD

**Issue by dudeonthehorse** [mohitsinghs/gulp-nunjucks-md#5]
Hello

I defined macro in my layout.njk

```
{% macro button(text, href) %}
<button href="{{href}}">{{text}}</button>
{% endmacro %}
```
If I call macro in the same layout like this

```
{{ button("text", "#") }}
```
It's works fine. 

But if I call macro in document
```
---
layout: layout
subject: Subject
preheader: Preheader text
---

{{ button("text", "#") }}
``` 
It throws an error: (unknown path) [Line 9, Column 35] parseSignature: expected comma after expression

**Comment by mohitsinghs** [comment]
Seems strange to me. I just tested the example you provided and it works fine with almost every version of plugin.

**Comment by dudeonthehorse** [comment]
Node version? I use v8

**Comment by mohitsinghs** [comment]
I too have node v8 installed.

**Comment by dudeonthehorse** [comment]
Please check out my clean project with the same problem https://github.com/dudeonthehorse/nunjucks-md

If you remove macro from example.md — gulp will running normally

**Comment by mohitsinghs** [comment]
Thank you for for your project. I was able to reproduce the problem. Initially, I wasn't able to reproduce the issue as I was using html instead of markdown.  This issue was caused by marked which escapes quotes by default. This plugin now uses a modified version of marked. This issue should be fixed now in the latest version of the plugin. 🎉

**Comment by dudeonthehorse** [comment]
Okay. I've reinstalled dependencies. But now we have a new problem

**default.njk**
```
{% macro link(text, href) %}
<a href="{{href}}">{{text}}</a>
{% endmacro %}

{% block content %}{% endblock %}
```

**example.md**
```
---
layout: default
subject: subject
preheader: preheader text
---

{{ link('First link', 'http://example.com/') }}

{{ link("Second link", "http://example.com/") }}
```

**output**
```
<a href="&lt;a href=&quot;http://example.com/&quot;&gt;http://example.com/&lt;/a&gt;">First link</a>

Error: (unknown path) [Line 3, Column 33] parseSignature: expected comma after expression
```

**Comment by dudeonthehorse** [comment]
In my previous project I used this method.

**input.html**
```
{% extends "extends/newsletter.html" %}
{% include "macro/macro.html" %}
{% block content %}
{% markdown %}

# Heading

Lorem ipsum text

{{ link('Hooray', 'http://example.com/') }}

{% endmarkdown %}
{% endblock %}
```

It worked great. But code looks shitty.

I used these packages:
- https://www.npmjs.com/package/gulp-nunjucks-render
- https://www.npmjs.com/package/nunjucks-markdown

**Comment by mohitsinghs** [comment]
This is the expected behavior. In *GFM ( Github Flavored Markdown )* links and emails are automatically converted into html. The problem here is that this plugin uses marked and by default marked have GFM enabled. You can disable gfm by passing an option like this –
```js
gulp.task('default', function() {
    return gulp.src('src/*.{html,njk,md}')
        .pipe(nunjucksMd({
            path: ['src/templates/'],
            marked: {
              gfm: false
            }
        }))
        .pipe(gulp.dest('dist'))
})
```
Another solution is to avoid such links in macros and use relative links instead.

**Comment by dudeonthehorse** [comment]
Thanks

**Comment by dudeonthehorse** [comment]
Good news. Now it works fine in gfm mode
